### PR TITLE
Add some basic functionality

### PR DESCRIPTION
**Pull request by LaVieEstDure**
Added default tokens and config file from Awesomebot V1, discord.py bot instance, running file

### CODE REVIEW

**Comment by seekheart** [comment]
should we figure out the file directory structure and stuff first?

**Comment by LaVieEstDure** [comment]
This is how most of the bots I've seen are arranged for the most part but yeah, should probably decide that. Though, its pretty easy to shuffle things around right now, so

**Comment by seekheart** [comment]
we should also decide on what libs to use? discord py + requests?

**Comment by seekheart** [comment]
if it's fine with you @LaVieEstDure we should probably have a workflow like git flow or feature branch?
It might get hairy later on if we don't have a workflow.

**Comment by seekheart** [comment]
gonna close this since #5 also addresses this

**Pull request closed without merging**
