### PR TITLE
#2 added basic structure and travis yml along with dependencies.

### LINKED ISSUE #2: Setup CI via Travis
Setup CI on travis

What python versions do we want to support? 3.6+?

### PR DESCRIPTION
**Pull request by seekheart**
This PR closes #2 with the addition of travis and also builds on #3 with a basic layout.

### CODE REVIEW

**Comment by seekheart** [comment]
The travis build will continue to fail for now because there aren't any tests to run. @LaVieEstDure can you add a dummy test?

**Review by Heasummn — APPROVED** [review]
Looks good to me, we have a basic setup for the structure of the bot and a basic system to run Travis checks.

**Comment by LaVieEstDure** [comment]
Looks good to me!

**Review by LaVieEstDure — APPROVED** [review]

**Comment by saethlin** [comment]
Why do we have so many entries in the requirements.txt already?

**Comment by seekheart** [comment]
There are peer dependencies I believe that needed to be installed with discord.py

**Pull request merged**
